apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: packetbeat
spec:
  type: packetbeat
  version: 7.8.0
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
  config:
    packetbeat.interfaces.device: any
    packetbeat.protocols:
    - type: icmp
      enabled: true
    - type: amqp
      ports: [5672]
    - type: cassandra
      ports: [9042]
    - type: dhcpv4
      ports: [67, 68]
    - type: dns
      ports: [53]
      include_authorities: true
      include_additionals: true
    - type: http
      ports: [80, 8000, 8080, 9200]
    - type: memcache
      ports: [11211]
    - type: mysql
      ports: [3306,3307]
    - type: pgsql
      ports: [5432]
    - type: redis
      ports: [6379]
    - type: thrift
      ports: [9090]
    - type: mongodb
      ports: [27017]
    - type: nfs
      ports: [2049]
    - type: tls
      ports:
      - 443   # HTTPS
      - 993   # IMAPS
      - 995   # POP3S
      - 5223  # XMPP over SSL
      - 8443
      - 8883  # Secure MQTT
      - 9243  # Elasticsearch
    packetbeat.flows:
      timeout: 30s
      period: 10s
    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
  daemonSet:
    podTemplate:
      spec:
        terminationGracePeriodSeconds: 30
        hostNetwork: true
        automountServiceAccountToken: true # some older Beat versions are depending on this settings presence in k8s context
        dnsPolicy: ClusterFirstWithHostNet
        containers:
        - name: packetbeat
          securityContext:
            runAsUser: 0
            capabilities:
              add:
              - NET_ADMIN
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.8.0
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.8.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
...
