kind: Service
apiVersion: v1
metadata:
  name: minio-one-nodeport
  namespace: minio-one
spec:
  selector:
    app: minio-one
  ports:
    - name: http
      port: 9000
  type: NodePort

---
kind: Service
apiVersion: v1
metadata:
  name: minio-two-nodeport
  namespace: minio-two
spec:
  selector:
    app: minio-two
  ports:
    - name: http
      port: 9000
  type: NodePort