version: "3.0"
services:
  sourceminio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio1
      MINIO_SECRET_KEY: minio1@123
    ports:
      - "9001:9000"
    volumes:
      - "./data1:/data"

  targetminio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio2
      MINIO_SECRET_KEY: minio2@123
    ports:
      - "9002:9000"
    volumes:
      - "./data2:/data"

  python_app:
    image: minio_target
    depends_on:
      - sourceminio
      - targetminio
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ## This environment variable is for to insturct application to run in loop or not
      IN_LOOP: "True"
      ## This envrionment variables are for the minio from where we will be downloading files.
      SOURCE_MINIO_URL: "http://sourceminio:9000"
      SOURCE_MINIO_ACCESS_KEY: minio1
      SOURCE_MINIO_SECRET_KEY: minio1@123
      SOURCE_MINIO_BUCKET: dummy
      ## Environment variables for logic if the files to be uploaded to target minio. If this envrionment is not provided default value is false
      UPLOAD_TO_TARGET: "True"
      ## This environment variables are for the minio to where the downloaded files will be uploaded.
      TARGET_MINIO_URL: "http://targetminio:9000"
      TARGET_MINIO_ACCESS_KEY: minio2
      TARGET_MINIO_SECRET_KEY: minio2@123
      TARGET_MINIO_BUCKET: dummy
    volumes:
      - "./files:/files"
