apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-to-minio
  namespace: minio-test
  labels:
    app: python-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-minio
  template:
    metadata:
      labels:
        app: python-minio
    spec:
      containers:
        - name: python-script
          image: xuxant/k8s_traffic_minio
          env:
            - name: IN_LOOP
              value: "True"
            - name: SOURCE_MINIO_URL
              value: "http://minio-one.minio-one:9000"
            - name: SOURCE_MINIO_ACCESS_KEY
              value: minio1
            - name: SOURCE_MINIO_SECRET_KEY
              value: minio1@123
            - name: SOURCE_MINIO_BUCKET
              value: dummy
            # Upload to the target Source
            - name: UPLOAD_TO_TARGET
              value: "true"
            # Source Minio Infromation
            - name: TARGET_MINIO_URL
              value: "http://minio-two.minio-two:9000"
            - name: TARGET_MINIO_ACCESS_KEY
              value: minio2
            - name: TARGET_MINIO_SECRET_KEY
              value: minio2@123
            - name: TARGET_MINIO_BUCKET
              value: dummy
            # Log Level (Default to Info)
            - name: LOG_LEVEL
              value: info
